version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  run:
    cmds:
      - rm -rf ./.tinygit
      - go run main.go init
  clean:
    cmds:
      - rm -rf ./.tinygit
      - rm -f ./tinygit
